# Generated by Django 5.1.2 on 2024-11-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panzofi_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='userImage',
            new_name='userUrlImage',
        ),
    ]
