# Generated by Django 5.1.2 on 2024-11-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panzofi_api', '0002_rename_userimage_author_userurlimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
