# Generated by Django 5.1.2 on 2024-11-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panzofi_api', '0005_alter_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReReply',
        ),
    ]
